// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.MVVMTest {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public partial class fdsaCommand : ViewModelCommand {
        
        private Single _Argument;
        
        public Single Argument {
            get {
                return _Argument;
            }
            set {
                _Argument = value;
            }
        }
    }
    
    public class LoginCommand : ViewModelCommand {
    }
    
    public partial class ChangeNameCommand : ViewModelCommand {
    }
}
