// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public abstract class uFrameMVVMPageBase : Invert.Core.GraphDesigner.DocumentationPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(uFrameMVVM);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "uFrameMVVM";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ElementPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(ElementNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Element";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ElementPropertiesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ElementPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(PropertiesChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Properties";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ElementCollectionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ElementPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(CollectionsChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Collections";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ElementCommandsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ElementPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(CommandsChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Commands";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ElementHandlersPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ElementPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(HandlersReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Handlers";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SimpleClassPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SimpleClassNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "SimpleClass";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SimpleClassPropertiesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SimpleClassPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(PropertiesChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Properties";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SimpleClassCollectionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SimpleClassPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(CollectionsChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Collections";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ViewPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(ViewNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "View";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ViewScenePropertiesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ViewPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SceneProperties);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Scene Properties";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ViewBindingsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ViewPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(BindingsReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Bindings";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ViewElementPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ViewPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(Element);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Element";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ComputedPropertyPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(ComputedPropertyNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "ComputedProperty";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ComputedPropertySubPropertiesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ComputedPropertyPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SubPropertiesReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Sub Properties";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SubsystemPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SubsystemNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Subsystem";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SubsystemImportPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SubsystemPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(Import);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Import";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SubsystemExportPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SubsystemPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(Export);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Export";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SubsystemInstancesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SubsystemPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(InstancesReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Instances";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SceneManagerPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SceneManagerNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "SceneManager";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SceneManagerSubsystemPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SceneManagerPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(Subsystem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Subsystem";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class SceneManagerSceneTransitionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(SceneManagerPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(SceneTransitionsReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Scene Transitions";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class MVVMPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(MVVMNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "MVVM";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class StateMachinePageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(StateMachineNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "StateMachine";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class StateMachineTransitionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(StateMachinePage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(TransitionsChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Transitions";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class StateMachineStartStatePageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(StateMachinePage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(StartState);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Start State";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class StatePageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(StateNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "State";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class StateStateTransitionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(StatePage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(StateTransitionsReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "State Transitions";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ViewComponentPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(ViewComponentNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "ViewComponent";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class CommandPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(CommandNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Command";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class CommandPropertiesPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(CommandPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(PropertiesChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Properties";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class CommandCollectionsPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(CommandPage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(CollectionsChildItem);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Collections";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ServicePageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return null;
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(ServiceNode);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Service";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
    
    public abstract class ServiceHandlersPageBase : uFrameMVVMPage {
        
        public override System.Type ParentPage {
            get {
                return typeof(ServicePage);
            }
        }
        
        public override System.Type RelatedNodeType {
            get {
                return typeof(HandlersReference);
            }
            set {
            }
        }
        
        public override string Name {
            get {
                return "Handlers";
            }
            set {
            }
        }
        
        public override void GetContent(Invert.Core.GraphDesigner.IDocumentationBuilder builder) {
            base.GetContent(builder);
        }
    }
}
