// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.MVVMTest {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class LandingPageScreenControllerBase : ScreenController {
        
        public override void Initialize(ViewModel viewModel) {
            this.InitializeLandingPageScreen(((LandingPageScreenViewModel)(viewModel)));
        }
        
        public virtual LandingPageScreenViewModel CreateLandingPageScreen() {
            return ((LandingPageScreenViewModel)(this.Create()));
        }
        
        public override ViewModel CreateEmpty() {
            return new LandingPageScreenViewModel(this);
        }
        
        public virtual void InitializeLandingPageScreen(LandingPageScreenViewModel viewModel) {
        }
    }
    
    public class WellnessSurveyScreenControllerBase : ScreenController {
        
        public override void Initialize(ViewModel viewModel) {
            this.InitializeWellnessSurveyScreen(((WellnessSurveyScreenViewModel)(viewModel)));
        }
        
        public virtual WellnessSurveyScreenViewModel CreateWellnessSurveyScreen() {
            return ((WellnessSurveyScreenViewModel)(this.Create()));
        }
        
        public override ViewModel CreateEmpty() {
            return new WellnessSurveyScreenViewModel(this);
        }
        
        public virtual void InitializeWellnessSurveyScreen(WellnessSurveyScreenViewModel viewModel) {
        }
    }
    
    public class ProgressScreenControllerBase : ScreenController {
        
        public override void Initialize(ViewModel viewModel) {
            this.InitializeProgressScreen(((ProgressScreenViewModel)(viewModel)));
        }
        
        public virtual ProgressScreenViewModel CreateProgressScreen() {
            return ((ProgressScreenViewModel)(this.Create()));
        }
        
        public override ViewModel CreateEmpty() {
            return new ProgressScreenViewModel(this);
        }
        
        public virtual void InitializeProgressScreen(ProgressScreenViewModel viewModel) {
        }
    }
}
