// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class SubsystemGraphBase : GenericGraphData<SubsystemNode> {
    }
    
    public class MVVMGraphBase : GenericGraphData<MVVMNode> {
    }
    
    public class StateMachineGraphBase : GenericGraphData<StateMachineNode> {
    }
    
    public class ServiceGraphBase : GenericGraphData<ServiceNode> {
    }
}
