// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.uFrame.MVVM {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Core.GraphDesigner;
    
    
    public class ElementNodeBase : Invert.Core.GraphDesigner.GenericInheritableNode, Invert.Core.GraphDesigner.IClassTypeNode, IViewConnectable, IInstancesConnectable {
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Commands", SectionVisibility.Always, OrderIndex=3, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CommandsChildItem> Commands {
            get {
                return ChildItems.OfType<CommandsChildItem>();
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Properties", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return ChildItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Collections", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return ChildItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface IElementConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class SimpleClassNodeBase : Invert.Core.GraphDesigner.GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Properties", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<PropertiesChildItem> Properties {
            get {
                return ChildItems.OfType<PropertiesChildItem>();
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Collections", SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<CollectionsChildItem> Collections {
            get {
                return ChildItems.OfType<CollectionsChildItem>();
            }
        }
    }
    
    public partial interface ISimpleClassConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class ViewNodeBase : Invert.Core.GraphDesigner.GenericInheritableNode, Invert.Core.GraphDesigner.IClassTypeNode, IViewComponentConnectable {
        
        private SceneProperties _SceneProperties;
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IBindingsConnectable> PossibleBindings {
            get {
                return this.Project.AllGraphItems.OfType<IBindingsConnectable>();
            }
        }
        
        [Invert.Core.GraphDesigner.ReferenceSection("Bindings", SectionVisibility.Always, false, false, typeof(IBindingsConnectable), false, OrderIndex=0, HasPredefinedOptions=true, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<BindingsReference> Bindings {
            get {
                return ChildItems.OfType<BindingsReference>();
            }
        }
        
        [Invert.Core.GraphDesigner.InputSlot("Scene Properties", false, SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual SceneProperties ScenePropertiesInputSlot {
            get {
                if (_SceneProperties == null) {
                    _SceneProperties = new SceneProperties() { Node = this };
                }
                return _SceneProperties;
            }
            set {
                _SceneProperties = value;
            }
        }
    }
    
    public partial interface IViewConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class ComputedPropertyNodeBase : Invert.Core.GraphDesigner.GenericNode, ITransitionsConnectable {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<ISubPropertiesConnectable> PossibleSubProperties {
            get {
                return this.Project.AllGraphItems.OfType<ISubPropertiesConnectable>();
            }
        }
        
        [Invert.Core.GraphDesigner.ReferenceSection("Sub Properties", SectionVisibility.Always, false, false, typeof(ISubPropertiesConnectable), false, OrderIndex=0, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<SubPropertiesReference> SubProperties {
            get {
                return ChildItems.OfType<SubPropertiesReference>();
            }
        }
    }
    
    public partial interface IComputedPropertyConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class SubsystemNodeBase : Invert.Core.GraphDesigner.GenericNode {
        
        private Import _Import;
        
        private Export _Export;
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IInstancesConnectable> PossibleInstances {
            get {
                return this.Project.AllGraphItems.OfType<IInstancesConnectable>();
            }
        }
        
        [Invert.Core.GraphDesigner.ReferenceSection("Instances", SectionVisibility.Always, false, false, typeof(IInstancesConnectable), true, OrderIndex=1, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<InstancesReference> Instances {
            get {
                return ChildItems.OfType<InstancesReference>();
            }
        }
        
        [Invert.Core.GraphDesigner.InputSlot("Import", true, SectionVisibility.WhenNodeIsNotFilter, OrderIndex=0, IsNewRow=true)]
        public virtual Import ImportInputSlot {
            get {
                if (_Import == null) {
                    _Import = new Import() { Node = this };
                }
                return _Import;
            }
            set {
                _Import = value;
            }
        }
        
        [Invert.Core.GraphDesigner.OutputSlot("Export", false, SectionVisibility.WhenNodeIsNotFilter, OrderIndex=0, IsNewRow=false)]
        public virtual Export ExportOutputSlot {
            get {
                if (_Export == null) {
                    _Export = new Export() { Node = this };
                }
                return _Export;
            }
            set {
                _Export = value;
            }
        }
    }
    
    public partial interface ISubsystemConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class SceneManagerNodeBase : Invert.Core.GraphDesigner.GenericNode, Invert.Core.GraphDesigner.IClassTypeNode {
        
        private Subsystem _Subsystem;
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<ISceneTransitionsConnectable> PossibleSceneTransitions {
            get {
                return this.Project.AllGraphItems.OfType<ISceneTransitionsConnectable>();
            }
        }
        
        [Invert.Core.GraphDesigner.ReferenceSection("Scene Transitions", SectionVisibility.Always, false, false, typeof(ISceneTransitionsConnectable), false, OrderIndex=1, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<SceneTransitionsReference> SceneTransitions {
            get {
                return ChildItems.OfType<SceneTransitionsReference>();
            }
        }
        
        [Invert.Core.GraphDesigner.InputSlot("Subsystem", false, SectionVisibility.Always, OrderIndex=0, IsNewRow=true)]
        public virtual Subsystem SubsystemInputSlot {
            get {
                if (_Subsystem == null) {
                    _Subsystem = new Subsystem() { Node = this };
                }
                return _Subsystem;
            }
            set {
                _Subsystem = value;
            }
        }
    }
    
    public partial interface ISceneManagerConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class MVVMNodeBase : Invert.Core.GraphDesigner.GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IMVVMConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class StateMachineNodeBase : Invert.Core.GraphDesigner.GenericNode, Invert.Core.GraphDesigner.IClassTypeNode {
        
        private StartState _StartState;
        
        public virtual string ClassName {
            get {
                return this.Name;
            }
        }
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        [Invert.Core.GraphDesigner.Section("Transitions", SectionVisibility.Always, OrderIndex=1, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<TransitionsChildItem> Transitions {
            get {
                return ChildItems.OfType<TransitionsChildItem>();
            }
        }
        
        [Invert.Core.GraphDesigner.OutputSlot("Start State", false, SectionVisibility.WhenNodeIsFilter, OrderIndex=0, IsNewRow=true)]
        public virtual StartState StartStateOutputSlot {
            get {
                if (_StartState == null) {
                    _StartState = new StartState() { Node = this };
                }
                return _StartState;
            }
            set {
                _StartState = value;
            }
        }
    }
    
    public partial interface IStateMachineConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class StateNodeBase : Invert.Core.GraphDesigner.GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
        
        public virtual System.Collections.Generic.IEnumerable<IStateTransitionsConnectable> PossibleStateTransitions {
            get {
                return this.Project.AllGraphItems.OfType<IStateTransitionsConnectable>();
            }
        }
        
        [Invert.Core.GraphDesigner.ReferenceSection("State Transitions", SectionVisibility.Always, false, false, typeof(IStateTransitionsConnectable), false, OrderIndex=0, HasPredefinedOptions=false, IsNewRow=true)]
        public virtual System.Collections.Generic.IEnumerable<StateTransitionsReference> StateTransitions {
            get {
                return ChildItems.OfType<StateTransitionsReference>();
            }
        }
    }
    
    public partial interface IStateConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
    
    public class ViewComponentNodeBase : Invert.Core.GraphDesigner.GenericNode {
        
        public override bool AllowMultipleInputs {
            get {
                return true;
            }
        }
        
        public override bool AllowMultipleOutputs {
            get {
                return true;
            }
        }
    }
    
    public partial interface IViewComponentConnectable : Invert.Core.GraphDesigner.IDiagramNodeItem, Invert.Core.GraphDesigner.IConnectable {
    }
}
