// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.MVVMTest {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    
    
    public class DailyWorkoutResultsViewBase : ViewBase {
        
        [UnityEngine.SerializeField()]
        [UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _FirstName;
        
        [UnityEngine.SerializeField()]
        [UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public String _LastName;
        
        [UnityEngine.SerializeField()]
        [UFGroup("View Model Properties")]
        [UnityEngine.HideInInspector()]
        public Boolean _IsSuperstar;
        
        [UFToggleGroup("FirstName")]
        [UnityEngine.HideInInspector()]
        public bool _BindFirstName = true;
        
        [UFGroup("FirstName")]
        [UnityEngine.SerializeField()]
        private UnityEngine.UI.InputField _FirstNameinput;
        
        [UFToggleGroup("LastName")]
        [UnityEngine.HideInInspector()]
        public bool _BindLastName = true;
        
        [UFGroup("LastName")]
        [UnityEngine.SerializeField()]
        private UnityEngine.UI.InputField _LastNameinput;
        
        [UFToggleGroup("Register")]
        [UnityEngine.HideInInspector()]
        public bool _BindRegister = true;
        
        [UFGroup("Register")]
        [UnityEngine.SerializeField()]
        private UnityEngine.UI.Button _Registerbutton;
        
        [UFToggleGroup("IsSuperstar")]
        [UnityEngine.HideInInspector()]
        public bool _BindIsSuperstar = true;
        
        [UFGroup("IsSuperstar")]
        [UnityEngine.SerializeField()]
        private UnityEngine.UI.Toggle _IsSuperstartoggle;
        
        public override System.Type ViewModelType {
            get {
                return typeof(DailyWorkoutResultsScreenViewModel);
            }
        }
        
        public DailyWorkoutResultsScreenViewModel DailyWorkoutResultsScreen {
            get {
                return (DailyWorkoutResultsScreenViewModel)ViewModelObject;
            }
        }
        
        public override ViewModel CreateModel() {
            return this.RequestViewModel(GameManager.Container.Resolve<DailyWorkoutResultsScreenController>());
        }
        
        protected override void InitializeViewModel(ViewModel model) {
            var dailyworkoutresultsview = ((DailyWorkoutResultsScreenViewModel)model);
            dailyworkoutresultsview.FirstName = this._FirstName;
            dailyworkoutresultsview.LastName = this._LastName;
            dailyworkoutresultsview.IsSuperstar = this._IsSuperstar;
        }
        
        public override void Bind() {
            if (_BindFirstName) {
                this.BindInputFieldToProperty(_FirstNameinput, this.DailyWorkoutResultsScreen.FirstNameProperty);
            }
            if (_BindLastName) {
                this.BindInputFieldToProperty(_LastNameinput, this.DailyWorkoutResultsScreen.LastNameProperty);
            }
            if (_BindRegister) {
                this.BindButtonToCommand(_Registerbutton, this.DailyWorkoutResultsScreen.Register);
            }
            if (_BindIsSuperstar) {
                this.BindToggleToProperty(_IsSuperstartoggle, this.DailyWorkoutResultsScreen.IsSuperstarProperty);
            }
        }
        

        
        public virtual void ExecuteRegister() {
            this.ExecuteCommand(DailyWorkoutResultsScreen.Register);
        }
    }
}
