// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Invert.MVVMTest {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    
    
    public class DailyWorkoutResultsScreenViewModelBase : FormViewModel {
        
        private P<String> _FirstNameProperty;
        
        private P<String> _LastNameProperty;
        
        private P<Boolean> _IsSuperstarProperty;
        
        private ICommand _Register;
        
        public DailyWorkoutResultsScreenViewModelBase(DailyWorkoutResultsScreenControllerBase controller, bool initialize = true) : 
                base(controller, initialize) {
        }
        
        public virtual P<String> FirstNameProperty {
            get {
                return _FirstNameProperty;
            }
            set {
                _FirstNameProperty = value;
            }
        }
        
        public virtual P<String> LastNameProperty {
            get {
                return _LastNameProperty;
            }
            set {
                _LastNameProperty = value;
            }
        }
        
        public virtual P<Boolean> IsSuperstarProperty {
            get {
                return _IsSuperstarProperty;
            }
            set {
                _IsSuperstarProperty = value;
            }
        }
        
        public virtual String FirstName {
            get {
                return FirstNameProperty.Value;
            }
            set {
                FirstNameProperty.Value = value;
            }
        }
        
        public virtual String LastName {
            get {
                return LastNameProperty.Value;
            }
            set {
                LastNameProperty.Value = value;
            }
        }
        
        public virtual Boolean IsSuperstar {
            get {
                return IsSuperstarProperty.Value;
            }
            set {
                IsSuperstarProperty.Value = value;
            }
        }
        
        public virtual ICommand Register {
            get {
                return _Register;
            }
            set {
                _Register = value;
            }
        }
        
        public override void Bind() {
            base.Bind();
            _FirstNameProperty = new P<String>(this, "FirstName");
            _LastNameProperty = new P<String>(this, "LastName");
            _IsSuperstarProperty = new P<Boolean>(this, "IsSuperstar");
        }
        
        protected override void WireCommands(Controller controller) {
            base.WireCommands(controller);
            var dailyworkoutresultsscreen = controller as DailyWorkoutResultsScreenController;
            this.Register = new CommandWithSender<DailyWorkoutResultsScreenViewModel>(this as DailyWorkoutResultsScreenViewModel, dailyworkoutresultsscreen.Register);
        }
        
        public override void Read(ISerializerStream stream) {
            base.Read(stream);
            this.IsSuperstar = stream.DeserializeBool("IsSuperstar");;
        }
        
        public override void Write(ISerializerStream stream) {
            base.Write(stream);
            stream.SerializeBool("IsSuperstar", this.IsSuperstar);
        }
        
        protected override void FillCommands(System.Collections.Generic.List<ViewModelCommandInfo> list) {
            base.FillCommands(list);
            list.Add(new ViewModelCommandInfo("Register", Register) { ParameterType = typeof(void) });
        }
        
        protected override void FillProperties(System.Collections.Generic.List<ViewModelPropertyInfo> list) {
            base.FillProperties(list);
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_FirstNameProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_LastNameProperty, false, false, false, false));
            // PropertiesChildItem
            list.Add(new ViewModelPropertyInfo(_IsSuperstarProperty, false, false, false, false));
        }
    }
}
